/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  access_token: string | null;
  expires_at: Int8 | null;
  id: Generated<string>;
  id_token: string | null;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  userId: string;
}

export interface Memberships {
  agreed_to_terms: Timestamp | null;
  ended_at: Timestamp | null;
  id: Generated<number>;
  joined_at: Timestamp | null;
  level: string | null;
  privacy_policy_ok: Timestamp | null;
  status: string | null;
  user_id: string | null;
}

export interface Payments {
  amount: number | null;
  created_at: Generated<Timestamp>;
  currency: string | null;
  id: string;
  stripe_payment_intent_id: string | null;
  subscription_id: string | null;
}

export interface Products {
  currency: string | null;
  id: string;
  interval: string | null;
  name: string | null;
  price: number | null;
  stripe_price_id: string | null;
  stripe_product_id: string | null;
}

export interface Sessions {
  expires: Timestamp;
  id: Generated<string>;
  sessionToken: string;
  userId: string;
}

export interface Subscriptions {
  cancel_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_period_end: Timestamp | null;
  current_period_start: Timestamp | null;
  id: string;
  product_id: string | null;
  status: string | null;
  stripe_subscription_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface Users {
  alias: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  emailVerified: Timestamp | null;
  full_name: string | null;
  handle: string | null;
  id: Generated<string>;
  image: string | null;
  name: string | null;
  stripe_customer_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface VerificationToken {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface DB {
  accounts: Accounts;
  memberships: Memberships;
  payments: Payments;
  products: Products;
  sessions: Sessions;
  subscriptions: Subscriptions;
  users: Users;
  verification_token: VerificationToken;
}
